" github:etc/vim/vimrc
" -*- Mode: Vimrc; tab-width: 4; indent-tabs-mode: nil; -*-
"
"       Separate out vim settings into files in ~/etc/vim/rc.

let &runtimepath = &runtimepath . "," . expand('<sfile>:p:h')
runtime! rc/*
