endpoint: https://issues.apache.org/jira
project: AIRFLOW
password-source: keyring
query-fields: assignee,created,priority,reporter,status,summary,updated,issuetype,comments,description,votes,created,customfield_10110,components,fixVersions
